name: Generate docs and push to another branch

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate docs and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run generate-docs # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs # The branch name where you want to push the assets
          FOLDER: docs # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
